// <auto-generated />
using Contagion.Storage.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contagion.Storage.Migrations
{
    [DbContext(typeof(ContagionDbContext))]
    [Migration("20200406052604_teb")]
    partial class teb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contagion.Storage.Models.User", b =>
                {
                    b.Property<long>("UserPhone")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Long")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserPhone");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserPhone = 1234567890L,
                            Lat = -13.12m,
                            Long = 16.32m
                        },
                        new
                        {
                            UserPhone = 987653432L,
                            Lat = 32.7286784m,
                            Long = -97.1046912m
                        },
                        new
                        {
                            UserPhone = 1912552132L,
                            Lat = 84.54m,
                            Long = -55.65m
                        },
                        new
                        {
                            UserPhone = 8888888888L,
                            Lat = 81.54m,
                            Long = -56.65m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
